### ISSUE TITLE
Make Instructions Require Updating

### ISSUE THREAD

**Issue by phillc73** [magi-project/magi#7]
On a reasonably vanilla Debian 8 install, following the instruction [here](https://github.com/magi-project/magi/blob/master/doc/readme-qt.rst), resulted in a few errors.
```
Package libdb4.8++-dev is not available, but is referred to by another package.
```
Without this package, the build fails with:
```
src/db.h:14:20: fatal error: db_cxx.h: No such file or directory
```
Fixed by installing libdb++-dev

My build also failed with:
```
src/uint256.h:14:19: fatal error: gmpxx.h: No such file or directory
```
Fixed by installing libgmp-dev

Also failed with:
```
src/net.cpp:19:32: fatal error: miniupnpc/miniwget.h: No such file or directory
```
Fixed by installing libminiupnpc-dev

Wihout libminiupnpc installed the pre-compiled magi-qt binary found in [this archive](http://coinmagi.org/files/magi-release/m-wallet-latest-linux.tar.gz) also fails to execute.

**Comment by feldenthorne** [comment]
I just added the references for libgmp-dev and libminiupnpc-dev to my pull request (https://github.com/magi-project/magi/pull/6), but I am hesitant to add libdb++-dev.

Libdb4.8 was apparently stripped entirely from Debian 8 (see https://launchpad.net/debian/jessie/+source/db4.8/+changelog), so a new version of Berkeley DB must be used... but using 5.1 would be preferable to the ++ package. Because support for wallet.db should be maintained between official builds, using a specific version of the database libraries is preferable to libdb++ because libdb++ is based on the unstable/testing build of libdb5.3, from what I understand.

From the point of view of the user, it doesn't matter which libdbXX-dev version you use to compile the wallet for yourself, but you might not be able to flop your wallet.dat over to the official binaries later, if it's necessary.

**Comment by phillc73** [comment]
I see the updated discussion on the main bitcointalk.org thread about this. Unfortunately, after registration the site attempts to extort Bitcoin from me because I connect through a VPN, before I can post.

Anyway, yes, libdb++ is linked to libdb5.3 in Debian 8. I'm assuming that eventually the official builds will move to libdb5.3. If there's a wallet migration issue, I could send coins to another address, in another wallet, rather than migrating the actual wallet. Thanks for the warning though.

I also note that libdb5.1 is in the Jessie repositories, but not libdb5.1-dev

**Comment by feldenthorne** [comment]
To offer an update, Joe said he was going to look into switching to BDB 5.3 instead of 5.1, but I assume there won't be much news for a day or two. Opening this issue actually brought to light that he was building the Mac wallet with BDB 6-something as well, so it will invariably improve the quality and usability of the wallets in the long run once everything is ironed out.

As for the Litecoin wallet, I believe you should have run into the same problem because it also requires libdb4.8++-dev, which you were having issues with. If you tried to build it after the Magi wallet, you already had libdb5.3++-dev installed, so it just used that. If you built the Litecoin wallet before this one, I'm not entirely sure what's different that would make it work.

**Comment by feldenthorne** [comment]
As a final update, it has been decided that all wallets will use BDB 4.8 in the future. Personal builds using different BDB versions are still entirely possible, but wallets generated by builds with incompatible BDB versions will not be readable by official clients.

If you want personal binaries that produce compatible wallets, you will need to build BDB 4.8.30.NC from its sources and link them during compilation.

**Comment by bauerj** [comment]
The "official" binaries from coinmagi.org are linked against libdb5.1 now.

**Comment by feldenthorne** [comment]
That is certainly interesting. I apologize for posting misinformation - presumably Joe backpedaled on the decision some time between May and today. Or perhaps his build environment gave him grief for some reason or another and he just decided to go with what worked before.

**Comment by bauerj** [comment]
@feldenthorne I'm sure you were right back then :smiley: Just wanted to inform everyone that things have changed.

Sorry, if I was unclear.

**Comment by feldenthorne** [comment]
Oh, no. I took no offense. I was just apologizing and offering a few guesses. Thank you for pointing this discrepancy out.

**Comment by magi-project** [comment]
db4.8 was decided to be used officially. I have made this the only version in my machine compiling the wallet. Please let me be aware which qt wallet is linked to 5.1.

https://github.com/magi-project/magi/blob/master/magi-qt.pro#L27

**Comment by joelao95** [comment]
There was a mistake in my linux VB box I have overlooked with changes from time to time. It is fixed to db4.8 now. Wallet downloads are here: 

https://github.com/magi-project/magi/releases/tag/v1.2.3.1
http://coinmagi.org/files/magi-release

**Comment by joelao95** [comment]
Updated notes for building with db4.8. Now I close this thread; for any further issues, please open another one. 

https://github.com/magi-project/magi/blob/master/doc/build-unix.md
